### ISSUE TITLE
Preliquidaciones no Impactan futuras liquidaciones

### ISSUE THREAD

**Issue by jlaragon** [mradosta/pragtico#1]
Estimados por ejmplo uno esta preliquidando un mes por ejm este mes 04-2016 y me piden un adelanto de vacaciones ...hastaque yono confirmo laliquidacion del mes .... no impacta en elcalculo de las liquidaciones hacia adelante hastaque no estan confirmadas lo mismo para sac ganancias etc....

Con lo cual la solucion es un tilde en lapreliquidacion  que haga impactar esa preliquidacion en un mes determinado

Espero que se entienda

**Comment by mradosta** [comment]
Nada en Pragtico se toma en cuenta hasta que no este confirmado. Agregar tildes en ciertos lugares y no en otros agregaria un complejidad adicional inncesaria.

**Comment by jlaragon** [comment]
En este caso esta el.ejemplo de una liquidacion final es muy  comun que los empleadores te piden calculo de liq  final por ejm al 31/05/16. Y si por ejm ese mes hace horas extras o se le liquidan vacaciones atrasadas y no esta confirmado el sistema al no tener  un tilde borrrador (por ejm hacer una liquidacion tildada como borrador que impacte en las remuneraciones de ese mes no va  atrabajar con las remuneracioned correctas tanto para indemnizaciones como para vac no gozadas . Y tambien si en  el mes se le paga vacaciones el promedio de los ultimos 6 meses  art 155 lct no estatia correcto hasta que la liq de ese mes no este confirmada.

**Comment by mradosta** [comment]
porque no seguir los pasos normales?
1) liquidar el mes
2) confirmar
3) hacer la liq final

**Comment by jlaragon** [comment]
Por que es muy comun que los.empleadores te piden calculo de liq finales si yomconfirmo mes y.no es la definitiva es un problema....luego hay eliminar.por base de datos. Con lo cual consider importante que se pueda preliquidar tipo borrador e impacte en las liq de vacaciones y finales y luego de ser correcta se confirma.

**Comment by mradosta** [comment]
La unica situacion que se me ocurre que una liq de mes no sea definitiva y deba "tocarse" es porque algo no esta 100% de acuerdo a la ley y se "dibuje a mano" algo. Pragtico solo se ajusta a la ley. Situaciones de borde no las contempla ni lo hara nunca.

**Comment by jlaragon** [comment]
Lo digo.con conocimiento.de causa trabajo en un estudio de liq de sueldos que calculamos liq finales todos los dias...como.borrador hay dos estados borrador que impacta en los calculos de mes si no se produce la baja luego se elimina sino se ajusta se destilda borrador y se liquida. Esta.fuera de ley es no liquidae como correspnde y no.tiene nada que ver el funcionamiento del sistema con la ley...

**Comment by jlaragon** [comment]
Estimados aca deberian agregar un boton de anulacion de liquidaciones pues se trabaja mucho con liq finales ( calculos) los cuales, deben impactar las liquidaciones y luego se sujeta a cambios Si hay que confirmar mes para que impacte en la liquidacion final es un problema....Si luego hay que cambiar 

Hay dos caminos :
-Boton para anular 
-Poder crear mas de una liquidacion por periodo y qeu la ultima pise a la anterior esto es impotarte por lo que mencione arriba
