### ISSUE TITLE
Bug en Concepto APorte Solidario Osecac

### ISSUE THREAD

**Issue by jlaragon** [mradosta/pragtico#11]
Estimado les paso un nuevo Bug pues es un descuento que va solo en la liquidacion Mensual,.. Solo en la de mes Destildo el resto en la parametrización y me la sigue liquidando te muestro esta tildada solo para la Normal .....

![image](https://cloud.githubusercontent.com/assets/18689760/16542276/da1df27e-4078-11e6-84d7-aa827e71048b.png)
Pero igual la trea en la liquidacion de Sac con lo cual hay que sacarla a mano..
![image](https://cloud.githubusercontent.com/assets/18689760/16542279/e4eba70a-4078-11e6-89e9-2b6cdaf7fb3e.png)

**Comment by mradosta** [comment]
El concepto figura en la liq tipo SAC porque la formula de algun otro concepto lo esta incluyendo.
Es un error en las formulas.

**Comment by jlaragon** [comment]
Estimado la verdad que no comprendo lo que detallas no se si es el medio o no este para manifestar mi duda, pido disculpas si no lo es... pero te copio todas las formulas de la relacion citada  en la cual podras notar que el concepto  "aporte_extraordinario" no esta en ninguna otra formula.
![image](https://cloud.githubusercontent.com/assets/18689760/16546691/de45f530-4128-11e6-864d-ea66548733df.png)

Pido disculpas si no es el medio este para poder manifesta la duda pero no comprendo...

Un cordial saludo

**Comment by jlaragon** [comment]
No sé si tiene  algo que ver que la jerarquía del concepto sea Relacion y No concepto pero eso supongo que se modifico cuando cambie la formula a mano en la relación para poder liquidar Junio correctamente pues ya no podia esperar mas tiempo.

**Comment by mradosta** [comment]
#12
