### ISSUE TITLE
Error en Concepto Aporte Solidario Osecac  Bug

### ISSUE THREAD

**Issue by jlaragon** [mradosta/pragtico#12]
Estimado la verdad que no comprendo lo que detallas no se si es el medio o no este para manifestar mi duda, pido disculpas si no lo es... pero te copio todas las formulas de la relacion citada en la cual podras notar que el concepto "aporte_extraordinario" no esta en ninguna otra formula.

![image](https://cloud.githubusercontent.com/assets/18689760/16547047/407ea902-4135-11e6-83fc-fea040e02fde.png)

Pido disculpas si no es el medio este para poder manifesta la duda pero no comprendo...

Un cordial saludo

**Comment by jlaragon** [comment]
No sé si tiene algo que ver que la jerarquía del concepto sea Relacion y No concepto pero eso supongo que se modifico cuando cambie la formula a mano en la relación para poder liquidar Junio correctamente pues ya no podia esperar mas tiempo.

**Comment by mradosta** [comment]
Puede ser que no lo veas en el detalle porque solo lista los conceptos directos, es decir, los conceptos que vienen en el recibo pero si hay un concepto que viene en el recibo que usa este concepto, eso no lo lista el detalle.
Busca por formula desde conceptos que por "aporte_extraordinario" y te listara todos los conceptos que lo usan y te permitira determinar cual es el concepto que esta mal

**Comment by mradosta** [comment]
#11
