### ISSUE TITLE
Suspensiones

### ISSUE THREAD

**Issue by jlaragon** [mradosta/pragtico#15]
Estimados dado que las suspensiones, son bastantes comunes, necesito saber si por el modulo de ausencias se puede cargar una suspensión parametrizarlos desde allí? Tal cual una licencia por enfermedad o similar?

O sea creo la variable #suspensión  y  automáticamente me va a salir en el menu de ausencias?

Desde ya muchas gracias

**Comment by jlaragon** [comment]
Detallo la paremetrizacion que hice de Suspensiones ... La duda que me queda es si en el caso que la suspension sea 1 dia solo un dia si pierde Presentismo  Premio

![image](https://cloud.githubusercontent.com/assets/18689760/17723386/17720934-6410-11e6-8ff7-1744ceae0c86.png)

Esta seria la formula del Presentismo incluyendo la Suspension
![image](https://cloud.githubusercontent.com/assets/18689760/17723452/a271b570-6410-11e6-95ab-22e8a1d6547f.png)


Bueno espero que si este no es el medio me digan donde crear el foro se puede hacer por CCT o por Concepto de Liquidacion

Quedo en naguardo


Un saludo

**Comment by jlaragon** [comment]
Quiero agregar que si son Jornales debe mostrar el sistema las suspensiones en horas y no en dias veo que solo trabaja el sistema conviertiendo horas a dias

![image](https://cloud.githubusercontent.com/assets/18689760/17760205/5c4a2a90-64d4-11e6-87fa-8158c4856aef.png)


![image](https://cloud.githubusercontent.com/assets/18689760/17760206/62a2a1b0-64d4-11e6-8c08-5b92a8c76fd3.png)


Seria bueno ver la posibilida que el sistema mueste en horas pues no sé como hacerlo que muestre en horas

**Comment by jlaragon** [comment]
Quedo en aguardo por este tema porque estoy en una base de produccion que , la cual me esta demandando ciertos detalles 

Quedo en aguardo de si puedo armar aqui mismo un foro

**Comment by mradosta** [comment]
Siempre queres que haga cosas en dias u horas segun sea jornalizado o no. Esto lo haces vos desde formula. Que pierda o no presentismo, igual, desde la formula de presentismo. No puedo darte soporte a formulas de tus propios conceptos.
