### ISSUE TITLE
Feriados Trabajadores Jornalizados

### ISSUE THREAD

**Issue by jlaragon** [mradosta/pragtico#16]
Estimados necesito saber como en el caso de un jornalizado por ejemplo le asigna un feriado ya sea 8 hs por feriado o 9 hs  y que se lo liquide como detallo abajo en imagen pues , el sistema por defecto no trae el tipo de  Hora Feriado..  al igual que en los Mensuales , no trae Dia Feriado para los Mensuales los cuales en comercio debe detallarse le feriado ya sea trabajado o no...
![image](https://cloud.githubusercontent.com/assets/18689760/17687778/abe5be52-634e-11e6-8d78-8d5a15196aeb.png)

Y que ademas en las cantidades se muestre Horas y No dias..

![image](https://cloud.githubusercontent.com/assets/18689760/17687806/e115d30a-634e-11e6-91d8-840b853f1e78.png)

Bueno desde ya agredeceré cualquier comentario si necesitan que las cosas las postee de otra manera me avisan como..

**Comment by jlaragon** [comment]
Continuando con este tema sigo dejando detalles que considero Importantes 

Si es Jornal se le liquida por hora es decir hay CCT que toman  8 hs o 9 Hs y bueno de ahi se toma la cantidad de Feriados que  tenga el mes es decir en este caso Agosto es 1 feriado 
  Te dejo el Ejemplo de un Jornal 

![image](https://cloud.githubusercontent.com/assets/18689760/17723260/1c825b32-640f-11e6-8e9e-15a5f995adeb.png)

 En Datos de los Feriados la cual me arroja un error al cargar un feriado y no entiendo la funcionalidad de esto... Y si impacta en las liquidaciones Lo que se necesitA  es qese feriado Cargado impact en Horas o dias como variable en el mes que se cargo o sea en este caso Agosto 1 dia Feriadopara Mensual o 8 u 9hs  para Jornales 

![image](https://cloud.githubusercontent.com/assets/18689760/17723275/385afaf8-640f-11e6-8a70-1da406690b21.png)

Si es Mensual se le paga el dia sobre Base de 25 es decir el Sueldso Bruto se le divide en 25 por la cantidad de feriados el cual arroja el Plus vacacional sobre un dia comun liquidado en base 30 dias
Dejo el ejemplo de un dia Mensuales de Feriado 
![image](https://cloud.githubusercontent.com/assets/18689760/17723281/46871a6c-640f-11e6-87b7-139b45be0b7f.png)


Bueno quedo en aguardo por Favor de este tema

Un saludo

**Comment by mradosta** [comment]
Todo lo que pedis / sugeris Pragtico lo soporta perfectamente. No puedo darte soporte a tus formulas propias.
