### ISSUE TITLE
Embargos 

### ISSUE THREAD

**Issue by jlaragon** [mradosta/pragtico#18]
Estimados cuando cargo un embardo en la liquidacion de mes lo genera perfecto 

Pero en la liquidacion final el concepto @descuento_embargo_sobre_smvm lo trae a cero , no sé si por codigo esta que en las liquidacion finales este concepto se liquide  a cero No lo sé  Bueno seria bueno saber si es asi..
Quedo en 
![embargo1](https://cloud.githubusercontent.com/assets/18689760/19414093/c43f54fa-9318-11e6-8bd0-866180a8015e.JPG)
![embargo2](https://cloud.githubusercontent.com/assets/18689760/19414094/c4fb6596-9318-11e6-97c1-8136852c031a.jpg)

**Comment by mradosta** [comment]
No puedo darte soporte sobre tus propios conceptos ya que cada implementacion puede tener su propia formula / configuracion. Solo sugerirte que te fijes el el concepto @descuento_embargo_sobre_smvm tenga tildado el tipo de liquidacion final tambien

**Comment by jlaragon** [comment]
Esta reposteado este Issue no es como detallan anteriormente
