### ISSUE TITLE
Cargar Variables  o Conceptos en la Preliquidacion

### ISSUE THREAD

**Issue by jlaragon** [mradosta/pragtico#2]
El sistema solo permite asignar a un relacion una variable o concepto a traves del menu relaciones

Pero seria importante ver la forma de cargarlo en la preliquidacion.... Pues, es muchoel tpo que uno pierde en asigar conceptos u variables ya que cada trabajador es un caso particular....

Bueno espero sus comentarios

A medida que vaya pudiendo ire reportanto todas las dudas o sugenrencias

**Comment by mradosta** [comment]
Agregar desde la preliquidacion puede ser confuso por dos motivos:
1) El liquidadaror no sabra si ese concepto se agrega solo para la pre-liquidacion actual o queda para siempre. Si queda para siempre, que lo haga desde donde corresponde (la relacion o los conceptos del empleador) puede no ser lo que quiere, si es para la actual no agrega valor valor ya se pierde cuando vuelve a pre-liquidar y debe hacer nuevamente el trabajo.
