### ISSUE TITLE
Liquidacion Final todo en un  mismo recibo

### ISSUE THREAD

**Issue by jlaragon** [mradosta/pragtico#5]
El sistema esta creado con Liquidaciones tipo Normar 1Q 2Q Final ,Vacaciones y Sac.. Si bien en la Final trae el Sac seria bueno poder hacer la liq Final en un solo recibo que salga todo Sac Propo Vacac No gozadas e Indem

Actualmetne para hacer Liq Final se liquida el propor Sueldo mes en Normal y Final en otro recibo a parte

Ver que solucion se le puede dar para que salga todo en un solo recibo

**Comment by mradosta** [comment]
Se hace en dos recibos separados porque no siempre se liquida / paga en el mismo momento. No veo una cuestion legal / funcional que requiera que salgan en un unico recibo. Sentite libre de re-abrir el ticket si consideras que podes aportar algo que no estoy viendo.
