### ISSUE TITLE
Vacaciones

### ISSUE THREAD

**Issue by jlaragon** [mradosta/pragtico#7]
Estimados no veo o al menos no sé como poder colocar correctamente una formula de vacaciones ya que la misam es un promedio variable de los ultimos 6 meses en caso dde haber rem variables ....

Y en el caso de no haber rem varible hay que tomar ultimi sueldo mas adicionales el cual no me esta tomando los adicionales no sé el por que... Al estar la liquiidacion de vacaciones separada de la mensual primero habia que confirmar mes... para liquidar vacaciones y que se acorrecta este calculo teniendo en cuenta que este mes por Ejm en Comercio hay aumento...

Espero sus comentarios

Por favor

**Comment by mradosta** [comment]
Tu consulta esta en el manual.
http://pragtico.pragmatia.com/wiki/index.php/Variables_(Listado)

Por favor, no puedo responder por este medio preguntas conceptuales de liquidacion de sueldos. Solo problemas / errores tecnicos.
